### PR TITLE
upgrade to deno 2.x 

### PR DESCRIPTION
**Pull request by nailuoGG**
### Motivation

- `deno-websocket` does not support setting the hostname to `localhost`, which causes the `macOS` system to ask the user for network permission.
- Deno 2.x provides a simple solution for handling WebSocket connections.
- It's time to publish on jsr.io

### Situation

This PR is still in progress. Any questions are welcome.

### Related PR

- [https://github.com/manateelazycat/deno-bridge/pull/3](https://github.com/manateelazycat/deno-bridge/pull/3)

### CODE REVIEW

**Comment by manateelazycat** [comment]
Please tell me if PR is ready, thanks!

**Comment by nailuoGG** [comment]
This PR is ready for review. 

However, there are a couple discussion points I'd like to highlight:

1. Should we publish to jsr.io (Deno's new package registry)?
2. Need to verify compatibility with Deno 2.0's changes around:
   - Dependency management
   - Permission controls

I've added relevant docs for reference below:


Please let me know your thoughts on these items.

https://jsr.io/docs/publishing-packages#creating-a-scope-and-package

https://docs.deno.com/runtime/reference/migration_guide/#managing-dependencies

**Comment by manateelazycat** [comment]
Thanks for patch

**Comment by P233** [comment]
It seems the new updates haven't been pushed to deno.land or published to jsr.io.

I recently encountered an issue: the new deno-bridge.el update only allows `127.0.0.1` but my Deno WebSocket server is still binding to `0.0.0.0`. Is this related to the outdated package versions?

Screenshot 2024-12-05 at 09 22 27

**Comment by nailuoGG** [comment]
There are two ways to import deno-bridge in your Deno project:

## JSR.io Import Method

1. JSR packages are organized by scopes. To publish to JSR.io, follow the [official scope creation guide](https://jsr.io/docs/publishing-packages#creating-a-scope-and-package).

2. Import example:

```typescript
import { DenoBridge } from "jsr:@windycat/deno-bridge";
const [appName, denoPort, emacsPort] = Deno.args;
const bridge = new DenoBridge({ appName, denoPort, emacsPort }, messageDispatcher);
```

Note: `@windycat` is a test scope and not the official package scope.

## Deno.land Import Method

1. The mod.ts file is essential for deno.land compatibility and must be restored.

TODO:

- [ ] Restore the deleted mod.ts file
- [ ] Update examples in the repository
- [ ] Complete publishing to both platforms

**Comment by nailuoGG** [comment]
@P233 The issue appears to be related to outdated package versions. 

As a workaround, I suggest rolling back deno-bridge.el to commit `ad0d7a9626f81509b9b3087723010a2a9a0fca37`. This version allows binding to `0.0.0.0` and restores the `deno run -A` command functionality:

https://github.com/manateelazycat/deno-bridge/blob/ad0d7a9626f81509b9b3087723010a2a9a0fca37/deno-bridge.el#L135-L139

**Comment by P233** [comment]
@nailuoGG That works, thank you!

**Pull request merged**
